from odoo import models, fields, api
from odoo.exceptions import ValidationError

class AccountMove(models.Model):
    _inherit = 'account.move'
    _description = 'Agregar los campos necesarios para registrar los pagos en la misma factura'


    x_efectivo = fields.Float(String="Importe Efectivo")
    x_imp_mp = fields.Float(String="Importe Mercado Pago")
    x_nro_mp = fields.Char(String="Nro. Transacción M.P.")
    x_imp_tarj = fields.Float(String="Importe Tarjeta.")
    x_nro_tarj = fields.Char(String="Nro cupón Tarjeta")
    x_neto = fields.Float(String="Neto a Cancelar",
                          compute='_compute_neto',  #Llamo al metodo de cálculo.
                          store =True, # Almaceno el valor en la base de datos.
                          readonly = True,
                          digits = 'Product Price', # Definimos precisión.
                          tracking = True, # Seguir los cambios en el historial.
)
    # Realizamos el cálculo cuando se actuacilza x_efectivo, x_imp_mp, x_imp_tarj, amount_total, adedudao.
    @api.depends('amount_total', 'x_efectivo', 'x_imp_mp','x_imp_tarj')
    def _compute_neto(self):
        self.x_neto = self.amount_total - self.x_efectivo - self.x_imp_mp - self.x_imp_tarj

